### ISSUE TITLE
Add ECF Go Live Date to the JSON

### ISSUE THREAD

**Issue by mlissner** [audiodude/court-version-scraper#3]
For a new project we're working on we have a list of older cases that we want to download from PACER. Some of these are in PACER and some are not, depending on the date of the content and when the go live date for the given jurisdiction was. 

If we could add the go live date to the JSON and HTML returned by this app, that'd be very useful, since we're trying to scope this project based on the amount of data we'll be able to download. 

No idea your interest in adding another field to the scraper, but I might be able to do it if you don't have interest but are willing to deploy an updated version of the code.

**Comment by audiodude** [comment]
Sure I can add that to the HTML and JSON.

**Comment by mlissner** [comment]
Fantastic!

**Comment by audiodude** [comment]
Okay I've added it, but you're not going to be happy. It's very messy: http://court-version-scraper.herokuapp.com/courts.json

Some are missing, and the formats are all over the place. Some are just the date that the latest version went live.

Hope this helps!

**Comment by mlissner** [comment]
PACER is spectacular in all ways. This is great, @audiodude. I can normalize it from here. Should I file a bug with the people that run PACER to tell them their data is crap? J/k, that'd never work.

**Comment by mlissner** [comment]
Oh, and I'm gonna close this! Thanks for helping out! This is super helpful.
